apiVersion: v1
kind: Service
metadata:
  name: compliwave-db
  labels:
    app: compliwave-db
spec:
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: compliwave-db 